# Generated by Django 3.0.7 on 2021-04-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='total_paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
