# Generated by Django 3.0.7 on 2021-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_auto_20210406_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
