# Generated by Django 3.0.7 on 2021-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_auto_20210406_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='parking_time',
            field=models.IntegerField(null=True),
        ),
    ]
